
### sleep request
GET http://localhost:3000/api/sleep
Authorization: Bearer {{jwt}}

### sleep request With Time
GET http://localhost:3000/api/sleep/99
Authorization: Bearer {{jwt}}

### debug
GET http://localhost:3000/api/debug
Authorization: Bearer {{jwt}}

### Static Image
GET http://localhost:3000/api/wookie
Authorization: Bearer {{jwt}}
