
### sleep request
GET {{host}}/demo/sleep
Authorization: Bearer {{token}}

### sleep request With Time
GET {{host}}/demo/sleep/99
Authorization: Bearer {{token}}

### debug
GET {{host}}/demo/debug
Authorization: Bearer {{token}}

### Static Image
GET {{host}}/demo/wookie
Authorization: Bearer {{token}}
