
### sleep request
GET {{host}}/sleep
Authorization: Bearer {{jwt}}

### sleep request With Time
GET {{host}}/sleep/99
Authorization: Bearer {{jwt}}

### debug
GET {{host}}/debug
Authorization: Bearer {{jwt}}

### Static Image
GET {{host}}/wookie
Authorization: Bearer {{jwt}}
