
### create token
POST {{host}}/token
Authorization: Bearer {{token}}

### create token with issuer and comment
@issuer =me
@comment =test
POST {{host}}/token?issuer={{issuer}}&comment={{comment}}
Authorization: Bearer {{token}}

### DELETE token
DELETE {{host}}/token/58d88cd9-6862-4fe3-9f89-ff339b7e07ab
Authorization: Bearer {{token}}

### GET token count
GET {{host}}/token
Authorization: Bearer {{token}}
