
### GET teamspeak users
GET {{host}}/ts/users
Accept: application/json
Authorization: Bearer {{jwt}}

### GET teamspeak user existing
GET {{host}}/ts/users/Wookie
Authorization: Bearer {{jwt}}

### GET teamspeak user non existing
GET {{host}}/ts/users/FooBar
Authorization: Bearer {{jwt}}





