
### GET teamspeak users
GET {{host}}/ts/users
Accept: application/json
Authorization: Bearer {{token}}

### GET teamspeak user existing
GET {{host}}/ts/users/Wookie
Authorization: Bearer {{token}}

### GET teamspeak user non existing
GET {{host}}/ts/users/FooBar
Authorization: Bearer {{token}}


### Kick teamspeak user existing
GET {{host}}/ts/users/Wookie
Authorization: Bearer {{token}}



