name: Quality Check

on:
  push:
    branches:
    - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      NODE_ENV: production
      CI: true

    steps:
    - uses: actions/checkout@v4

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: "latest"

    - name: Install dependencies
      run: bun install

    - name: Run typecheck
      run: tsc

    - name: Run lint
      run: bun run lint:CI

    - name: Run test
      run: bun test
